# data variables
API_ENDPOINT: "https://fantasy.premierleague.com/api/fixtures/?event=1"

# GCP & Dataflow variables
PROJECT_ID: "gcp-practice-project-aman"
REGION: "us-central1"
RUNNER: "DataflowRunner"
JOB_NAME: "fantasy-premier-league-dataflow-job"

# Cloud Storage variables
GCS_TEMP_LOCATION: "gs://dataflow-bucket-gcp-practice-project-aman/temp"

# BigQuery variables
DATASET_NAME: "raw_layer"
TABLE_NAME: "fantasy_premier_league_fixtures"
# dataflow-bucket-gcp-practice-project-aman/templates/fixtures_template.json
# gs://dataflow-bucket-gcp-practice-project-aman/staging
# gs://dataflow-bucket-gcp-practice-project-aman/temp
# api_endpoint: https://fantasy.premierleague.com/api/fixtures/?event=1
# dataset: raw_layer
# table: sample_fpl_table
# schema: event:INTEGER,kickoff_time:DATETIME,started:BOOLEAN,team_h:INTEGER,team_a:INTEGER
