name: Google Provided Batch Job - GCS to BigQuery - via Terraform
on: workflow_dispatch # to be triggered manually

jobs:
  run-template:
    name: Dataflow Template
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 02-google-template/01-batch-jobs/gcs-to-bigquery/01-text-file/02-via-terraform

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # authenticate with gcloud
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SA_EMAIL }}

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan

      # Builds or changes infrastructure
      - name: Terraform Apply
        run: terraform apply -auto-approve
