name: Test

on: workflow_dispatch # to be triggered manually

jobs:
  run-template:
    name: Test Template
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 02-google-template/01-batch-jobs/gcs-to-bigquery/01-text-file/01-via-github-actions

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # load yaml file
      - name: Load environment from YAML
        run: |
          ENV_VARS=$(/config/github-actions-var.yaml)
