name: Build and Run Dataflow Job

on:
  push:
    branches:
      - master
    paths:
      - config/**

jobs:
  deploy-run-dataflow-job:
    name: Build and Run Dataflow Job
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SA_EMAIL }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Build the Dataflow Job
        run: |
          gcloud dataflow flex-template build \
          gs://dataflow-bucket-gcp-practice-project-aman/templates/fixtures_template.json \
          --sdk-language "PYTHON" \
          --image "us-central1-docker.pkg.dev/gcp-practice-project-aman/dataflow-templates/fpl-dataflow-template:v3"
