name: GCP Authentication

on:
  - workflow_call
  - workflow_dispatch

jobs:
  gcp-auth-and-terraform:
    name: GCP Auth
    runs-on: ubuntu-latest
    outputs:
      gcp-token: ${{ steps.auth.outputs.access_token }}

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SA_EMAIL }}
          token_format: access_token
